services:
  - type: web
    name: couchdb1
    env: docker
    envVars:
      - fromGroup: couchdb-settings
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10  
  - type: web
    name: couchdb2
    env: docker
    envVars:
      - fromGroup: couchdb-settings
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10

envVarGroups:
  - name: couchdb-settings
    envVars:
      - key: COUCHDB_PASSWORD
        generateValue: true 
      - key: COUCHDB_SECRET
        generateValue: true 
      - key: NODENAME
        generateValue: true 
      - key: COUCHDB_USER
        value: admin