services:
  - type: web
    name: couchdb1
    env: docker
    envVars:
      - key: NODENAME
        sync: false
      - key: QUOTAGUARDSTATIC_URL
        value: http://jk3c6j08ar3q06:fm54qmggeh6cpysb726ysscnp1qc@us-west-static-01-a.quotaguard.com:9293
      - fromGroup: couchdb-settings
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10  
  - type: web
    name: couchdb2
    env: docker
    envVars:
      - key: NODENAME
        sync: false
      - key: QUOTAGUARDSTATIC_URL
        value: http://jk3c6j08ar3q06:fm54qmggeh6cpysb726ysscnp1qc@us-west-static-01-b.quotaguard.com:9293
      - fromGroup: couchdb-settings
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10

envVarGroups:
  - name: couchdb-settings
    envVars:
      - key: COUCHDB_PASSWORD
        generateValue: true 
      - key: COUCHDB_SECRET
        generateValue: true 
      - key: NODENAME
        generateValue: true 
      - key: COUCHDB_USER
        value: admin